"""English dictionary."""

from typing import Any

EN: dict[str, Any] = {
    # Menu & Commands
    "cmd_start": "👋 Hi, {name}!\nI'm **Porabot**. I'll help you stop procrastinating.\n\nChoose an action from the menu 👇",
    "btn_new_task": "➕ New Task",
    "btn_my_tasks": "📅 My Tasks",
    "btn_settings": "⚙️ Settings",
    "btn_habits": "🫧 Habits",

    # Language Selection
    "choose_language": "Please choose a language / Пожалуйста, выберите язык:",
    "lang_ru": "🇷🇺 Русский",
    "lang_en": "🇬🇧 English",
    "lang_es": "🇪🇸 Español",
    "lang_set": "✅ Language set to English.",

    # Settings
    "settings_text": "⚙️ **Settings**\n\n🌍 Your timezone: `{timezone}`\n🗣 Interface language: English\n😴 Quiet hours: `{quiet_hours}`\n\nIf reminder times jump around, check your timezone.",
    "btn_change_tz": "🌍 Change Timezone",
    "btn_change_lang": "🗣 Change Language",
    "btn_quiet_hours_setup": "😴 Quiet hours",
    "btn_quiet_on": "😴 Quiet hours: ON",
    "btn_quiet_off": "😴 Quiet hours: OFF",
    "btn_quiet_start": "🌙 Start: {time}",
    "btn_quiet_end": "🌅 End: {time}",
    "quiet_hours_summary": "{status} ({start}–{end})",
    "quiet_time_prompt": "Please type quiet-hours time in HH:MM format (e.g. `23:00`).",
    "quiet_time_invalid": "❌ Please enter time in HH:MM format (e.g. `23:00`).",
    "quiet_time_saved": "✅ Quiet-hours time updated: `{time}`",
    "choose_tz": "Choose your timezone:",
    "tz_manual_prompt": "Send timezone (IANA), e.g. `Europe/London` or `America/New_York`. Short aliases like `EST`/`ET` are also accepted.",
    "tz_success": "✅ Timezone: `{tz}`",
    "tz_invalid": "❌ Unknown timezone. Use IANA format like `Europe/London` or `America/New_York`, or short alias like `EST`/`ET`.",
    "btn_toggle_utc_off": "🕒 Show UTC offset: OFF",
    "btn_toggle_utc_on": "🕒 Show UTC offset: ON",
    "btn_clear_all": "🗑 Clear all",
    "btn_clear_all_confirm": "✅ Yes, clear all",
    "btn_clear_all_cancel": "↩ Cancel",
    "clear_all_confirm_text": "⚠️ This will delete **all** your tasks, habits, and settings permanently.\n\nAre you sure?",
    "clear_all_done": "✅ All your data was deleted. Let's start from scratch.",
    
    # Custom Daily Briefs Settings
    "btn_briefs_setup": "📋 Briefs setup",
    "btn_briefs_on": "🔔 Daily Briefs: ON",
    "btn_briefs_off": "🔕 Daily Briefs: OFF",
    "btn_morning_brief": "🌅 Morning: {time}",
    "btn_evening_brief": "🌙 Evening: {time}",
    "choose_hour": "Please type the exact time (e.g. '09:30' or '23:45'):",
    "btn_back_settings": "🔙 Back",

    # Tasks List
    "no_tasks": "🎉 You have no active tasks. Relax!",
    "tasks_header": "📋 **Your tasks:**\n",
    "btn_delete_prefix": "🗑 Delete:",
    "btn_refresh": "🔄 Refresh",
    "btn_close": "❌ Close",

    # Wizard
    "enter_task": "Write what to remind you about.\nYou can include time: *\"Call mom tomorrow at 18:00\"*.",
    "parse_error": "Error parsing text. Check the format.",
    "ask_time": "Ok, task: \"{text}\".\nWhen to remind?",
    "try_again_manual": "Try again to write the FULL task, including date and time.",

    # Confirmation logic -> Edit logic
    "preview": "✅ **Task saved!**\n📌 {text}\n⏰ {time}",
    "btn_repeat_prefix": "🔁 Repeat:",
    "btn_nagging_prefix": "{icon} Nagging:",
    "btn_nagging_repeats_prefix": "🔁 Nag repeats: {count}",
    "btn_delete": "🗑 Delete",
    "btn_task_settings": "⚙️ Settings",
    "status_on": "ON",
    "status_off": "OFF",
    "repeat_none": "None",
    "repeat_day": "Daily",
    "repeat_weekdays": "Weekdays",
    "repeat_week": "Weekly",

    "main_menu_fallback": "Main menu",
    "task_deleted": "❌ Task deleted.",  # single definition — canonical value
    "what_next": "What next?",
    "cmd_cancel": "❌ Reminder creation cancelled.",
    "btn_cancel": "❌ Cancel",

    # Time Selection Keyboard
    "time_morning": "🌅 Morning",
    "time_day": "☀️ Day",
    "time_evening": "🌙 Evening",
    "time_night": "🌌 Night",
    "time_tomorrow": "🗓 Tomorrow (09:00)",
    "time_manual": "⌨️ Enter manually",

    # Reminders / Scheduler
    "reminder_prefix": "🔔 ",
    "brief_morning": "🌅 **Good morning! Plan for today:**\n",
    "brief_evening_title": "🌙 **Day summary:**",
    "brief_evening_done": "✅ Done: {count}",
    "brief_evening_pending": "⏳ Remaining/Missed: {count}\n",
    "btn_done": "✅ Done",
    "btn_done_add_note": "📝 Add note",
    "btn_done_skip_next": "⏭ Skip next",
    "btn_done_undo": "↩ Undo",
    "btn_snooze": "⏰ Snooze",
    "task_done_replies": [
        "✅ **You go!**",
        "✅ **Great!**",
        "✅ **Nice progress!**",
        "✅ **Strong move!**",
        "✅ **You nailed it!**",
        "✅ **Love that momentum!**",
        "✅ **Another win!**",
    ],
    "task_done_reply": "✅ **Good job. I'll leave you alone.**",
    "already_done": "Already done ✅",
    "snoozed_until": "⏰ Snoozed until {time}",
    "done_note_prompt": "Send a short completion note.",
    "done_note_saved": "✅ Note saved.",
    "done_skip_next_done": "⏭ Next occurrence skipped. New time: {time}",
    "done_skip_next_failed": "❌ I couldn't skip next occurrence for this task.",
    "done_undo_done": "↩ Done action was undone. Task is active again.",
    "task_settings_title": "⚙️ Settings for: {text}",
    "nagging_limit_prompt": "How many follow-up nag messages should I send for this task? Send a number from {min} to {max}. Current: {count}.",
    "nagging_limit_invalid": "❌ Please send a number from {min} to {max}.",
    "nagging_limit_updated": "✅ Nagging repeats limit set to: {count}",

    # Snooze options
    "snooze_15m": "+15m",
    "snooze_30m": "+30m",
    "snooze_1h": "+1h",
    "snooze_2h": "+2h",
    "snooze_1d": "+1 day",
    "snooze_morning": "🌅 Morning",
    "snooze_day": "☀️ Day",
    "snooze_evening": "🌙 Evening",
    "snooze_night": "🌌 Night",
    "snooze_custom": "⌨️ Custom",
    "parse_confirmation_prompt": "I might have parsed this ambiguously.\n\n📌 Task: {text}\n⏰ Time: {time}\n🎯 Confidence: {confidence}%\n\nIs this correct?",
    "btn_parse_confirm_yes": "✅ Yes",
    "btn_parse_confirm_time": "🕒 Pick time",
    "btn_parse_confirm_cancel": "❌ Cancel",

    # Missed-task recovery
    "missed_recovery_title": "📎 **Missed-task recovery**\nYou still have {count} overdue tasks:",
    "btn_recovery_done_all": "✅ Done all",
    "btn_recovery_snooze_all": "⏰ +1h all",
    "recovery_done_all_done": "✅ Marked {count} overdue tasks as done.",
    "recovery_snooze_all_done": "⏰ Snoozed {count} overdue tasks by 1 hour.",

    # Completed tasks section
    "btn_completed_tasks": "📜 Completed",
    "no_completed_tasks": "🧨 No completed tasks yet. Let's change that!",
    "completed_header": "🏆 **Completed tasks (last 7 days):**\n",
    "btn_done_task_prefix": "✅ Done:",

    # Habits
    "habits_dashboard": "🫧 **Habits Dashboard**:\nChoose a preset or create your own custom daily habit.",
    "habit_motivation": "🔥 Momentum: {weekly_done} completions in 7d · {active_count} active habits · streak {best_current_streak} (best {best_ever_streak})",
    "habit_preset_water": "💧 Drink water",
    "habit_preset_workout": "🧘 Workout",
    "habit_preset_rest": "🛌 Rest",
    "habit_btn_custom": "➕ Custom Habit",
    "habit_btn_fluid": "🌊 Fluid Habit",
    "habit_btn_list": "📋 My Active Habits",
    "habit_btn_cancel": "❌ Cancel",
    "habit_cancelled": "Cancelled.",
    "habit_unknown": "❓ Habit",
    "habit_selected_prompt": "You selected: **{habit}**\n\nWhat time every day should I remind you? (e.g. `10:00`)",
    "habit_custom_prompt": "What custom habit do you want to build?\n*(e.g. \"Read 20 pages\" or \"Study Python\")*",
    "habit_time_prompt": "Great! What time every day should I remind you? (e.g. `10:00`)",
    "habit_default_name": "My Habit",
    "habit_time_retry": "❌ I couldn't understand the time. Please try again (e.g. `10:00`).",
    "habit_created": "✅ **Daily Habit Created!**\nI will remind you to **{habit}** every day at `{time}`.",
    "habit_fluid_name_prompt": "🌊 Send the name of your fluid habit.\n\nExample: `Read 20 pages`",
    "habit_fluid_mode_prompt": "Choose fluid habit mode:",
    "habit_fluid_mode_brief_only": "1) Morning brief + evening check",
    "habit_fluid_mode_ask_time": "2) Ask me each morning for reminder time",
    "habit_fluid_created": "✅ **Fluid habit created!**\nHabit: **{habit}**\nMode: {mode}",
    "habit_create_failed_long": "❌ Failed to create habit (text too long).",
    "habit_create_failed_internal": "❌ Internal error creating habit.",
    "habit_no_active": "📋 You have no active daily habits. Click '➕ Custom Habit' or choose a preset to create one!",
    "habit_list_header": "📋 **Your Active Daily Habits:**\n",
    "habit_list_item": "{index}. **{habit}** ({time}) · 🔥 {streak} (best {best}) · {mode}",
    "habit_btn_delete_n": "❌ Delete {index}",
    "habit_btn_back_dashboard": "🔙 Back to Dashboard",
    "habit_deleted_alert": "✅ Habit successfully deleted!",
    "habit_deleted_followup": "Habit deleted. Click 🫧 Habits to view your updated dashboard.",
    "habit_delete_error_alert": "❌ Error deleting habit.",
    "habit_mode_fixed": "fixed time",
    "habit_mode_fluid_ask_time": "fluid: ask time daily",
    "habit_mode_fluid_brief_only": "fluid: brief-only",
    "habit_fluid_time_anytime": "anytime today",
    "fluid_morning_title": "🌊 **Fluid habits for today:**",
    "fluid_pick_time_prompt": "🌊 **Plan your fluid habit:**\nPick today’s reminder time for: **{habit}**",
    "fluid_evening_check": "🌙 **Before evening wrap-up:**\nMark completed fluid habits:",
    "fluid_done_btn_prefix": "✅ Done: ",
    "fluid_done_saved": "✅ Marked as done for today.",
    "fluid_time_custom": "⌨️ Custom time",
    "fluid_time_custom_prompt": "Send today’s reminder time in `HH:MM` format (e.g. `14:30`).",
    "fluid_time_invalid": "❌ Please use HH:MM (for example `14:30`).",
    "fluid_time_past": "❌ This time has already passed today.",
    "fluid_time_saved": "✅ I’ll remind you today at `{time}`.",
    
    # Error messages (SECURITY FIX: Added missing keys)
    "text_too_long": "❌ Text too long ({length} chars). Maximum: {max_length} chars.",
    "schedule_error": "❌ Failed to schedule reminder. Please try again.",
}
