"""Spanish dictionary (based on EN fallback with key Spanish overrides)."""

from typing import Any

from bot.lexicon.en import EN

ES: dict[str, Any] = dict(EN)
ES.update(
    {
        # Menu & Commands
        "cmd_start": "👋 Hola, {name}!\nSoy **Porabot**. Te ayudaré a procrastinar menos.\n\nElige una acción del menú 👇",
        "cmd_help": (
            "🤖 **Comandos de Porabot**\n\n"
            "/start — mostrar el menú principal\n"
            "/help — este mensaje\n"
            "/cancel — cancelar la acción actual\n\n"
            "Escribe o reenvía un mensaje como *«recuérdame en 15 minutos beber agua»* "
            "y detectaré la hora por ti. Usa los botones del menú para tareas, hábitos y ajustes."
        ),
        "cmd_desc_start": "Menú principal",
        "cmd_desc_help": "Mostrar ayuda",
        "cmd_desc_cancel": "Cancelar la acción actual",
        "btn_new_task": "➕ Nueva tarea",
        "btn_my_tasks": "📅 Mis tareas",
        "btn_settings": "⚙️ Ajustes",
        "btn_habits": "🫧 Hábitos",

        # Language Selection
        "choose_language": "Por favor, elige un idioma / Please choose a language:",
        "lang_ru": "🇷🇺 Русский",
        "lang_en": "🇬🇧 English",
        "lang_es": "🇪🇸 Español",
        "lang_set": "✅ Idioma cambiado a Español.",

        # Settings
        "settings_text": "⚙️ **Ajustes**\n\n🌍 Tu zona horaria: `{timezone}`\n🗣 Idioma de la interfaz: Español\n😴 Horas de silencio: `{quiet_hours}`\n\nSi la hora de recordatorios cambia, revisa tu zona horaria.",
        "btn_change_tz": "🌍 Cambiar zona horaria",
        "btn_change_lang": "🗣 Cambiar idioma",
        "btn_quiet_hours_setup": "😴 Horas de silencio",
        "btn_quiet_on": "😴 Horas de silencio: ON",
        "btn_quiet_off": "😴 Horas de silencio: OFF",
        "btn_quiet_start": "🌙 Inicio: {time}",
        "btn_quiet_end": "🌅 Fin: {time}",
        "quiet_hours_summary": "{status} ({start}–{end})",
        "quiet_time_prompt": "Escribe la hora de silencio en formato HH:MM (por ejemplo `23:00`).",
        "quiet_time_invalid": "❌ Introduce la hora en formato HH:MM (por ejemplo `23:00`).",
        "quiet_time_saved": "✅ Hora de silencio actualizada: `{time}`",
        "choose_tz": "Elige tu zona horaria:",
        "tz_manual_prompt": "Envía solo el desfase UTC: `+5`, `0`, `-6`, o un desfase de media hora conocido como `+5:30`.",
        "tz_manual_button": "⌨️ Introducir manualmente",
        "tz_success": "✅ Zona horaria: `{tz}`\n\nLas tareas existentes no se recalculan — sonarán a su hora anterior. Ajústalas manualmente si es necesario.",
        "tz_invalid": "❌ Desfase inválido. Envía `+5`, `0` o `-6` (rango: -12 a +14).",
        "tz_label_america_new_york": "Este de EE. UU. (EST/EDT)",
        "tz_label_america_chicago": "Centro de EE. UU. (CST/CDT)",
        "tz_label_america_denver": "Montaña de EE. UU. (MST/MDT)",
        "tz_label_america_los_angeles": "Pacífico de EE. UU. (PST/PDT)",
        "tz_label_europe_london": "Londres (GMT/BST)",
        "tz_label_europe_berlin": "Berlín (CET/CEST)",
        "tz_label_europe_kyiv": "Kyiv",
        "tz_label_europe_moscow": "Moscú",
        "tz_label_asia_dubai": "Dubái",
        "tz_label_asia_almaty": "Almaty",
        "tz_label_asia_tokyo": "Tokio",
        "tz_label_asia_singapore": "Singapur",
        "tz_label_utc": "UTC",
        "btn_toggle_utc_off": "🕒 Mostrar desplazamiento UTC: OFF",
        "btn_toggle_utc_on": "🕒 Mostrar desplazamiento UTC: ON",
        "btn_export_data": "📤 Exportar datos",
        "export_data_caption": "📤 Tu exportación de datos: tareas, hábitos y ajustes.",
        "export_data_error": "❌ No se pudo exportar los datos. Intenta más tarde.",
        "btn_clear_all": "🗑 Borrar todo",
        "btn_clear_all_confirm": "✅ Sí, borrar todo",
        "btn_clear_all_cancel": "↩ Cancelar",
        "clear_all_confirm_text": "⚠️ Esto eliminará **todas** tus tareas, hábitos y ajustes de forma permanente.\n\n¿Seguro?",
        "clear_all_done": "✅ Todos tus datos se eliminaron. Empezamos desde cero.",
        "btn_briefs_setup": "📋 Configurar resúmenes",
        "btn_briefs_on": "🔔 Resúmenes diarios: ON",
        "btn_briefs_off": "🔕 Resúmenes diarios: OFF",
        "btn_morning_brief": "🌅 Mañana: {time}",
        "btn_evening_brief": "🌙 Noche: {time}",
        "choose_hour": "Escribe la hora exacta (por ejemplo '09:30' o '23:45'):",
        "btn_back_settings": "🔙 Atrás",

        # Basics
        "what_next": "¿Qué sigue?",
        "cmd_cancel": "❌ Creación de recordatorio cancelada.",
        "btn_cancel": "❌ Cancelar",
        "no_tasks": "🎉 No tienes tareas activas.",
        "tasks_header": "📋 *Tus tareas:*\n",
        "tasks_page_indicator": "📄 {page}/{total}",
        "btn_prev_page": "◀️",
        "btn_next_page": "▶️",
        "btn_delete_prefix": "🗑 Eliminar:",
        "btn_refresh": "🔄 Actualizar",
        "btn_close": "❌ Cerrar",
        "enter_task": "Escribe qué debo recordarte.\nPuedes incluir hora: *\"Llamar a mamá mañana a las 18:00\"*.",
        "parse_error": "Error al procesar el texto. Revisa el formato.",
        "ask_time": "Vale, tarea: \"{text}\".\n¿Cuándo te lo recuerdo?",
        "try_again_manual": "🕒 Escribe la hora, por ejemplo `18:30` o `mañana a las 9`.",
        "time_in_past": "⏰ Esta hora ya pasó. Elige una hora futura.",
        "choosing_time_retry": "🕒 No encontré una hora en eso. Inténtalo de nuevo, por ejemplo `18:30` o `mañana a las 9`.",
        "forwarded_from": "Reenviado de",
        "text_only_hint": "📝 Por ahora solo entiendo texto. Envía tu recordatorio como mensaje de texto.",
        "preview": "✅ *¡Tarea guardada\\!*\n📌 {text}\n⏰ {time}",
        "btn_repeat_prefix": "🔁 Repetir:",
        "btn_nagging_prefix": "{icon} Insistencia:",
        "btn_nagging_repeats_prefix": "🔁 Repeticiones de insistencia: {count}",
        "btn_edit_time": "🕒 Cambiar hora",
        "btn_delete": "🗑 Eliminar",
        "btn_task_settings": "⚙️ Ajustes",
        "status_on": "ACTIVO",
        "status_off": "INACTIVO",
        "repeat_none": "Ninguna",
        "repeat_day": "Diaria",
        "repeat_weekdays": "Días laborables",
        "repeat_week": "Semanal",
        "repeat_weekend": "Fin de semana",
        "repeat_every_n_days": "Cada {n} días",
        "repeat_every_n_weeks": "Cada {n} semanas",
        "repeat_monthly_day": "Día {day} del mes",
        "repeat_last_weekday": "Último día laborable del mes",
        "repeat_month": "Mensual",
        "repeat_end_none": "sin límite",
        "repeat_end_count_label": "{count} veces",
        "repeat_end_until_label": "hasta {date}",

        # Constructor de repetición (RRULE) — 3.1
        "repeat_builder_title": "🔁 Configura la repetición:",
        "btn_repeat_none": "🚫 Sin repetición",
        "btn_repeat_daily": "📆 Cada día",
        "btn_repeat_weekdays_opt": "💼 Días laborables (Lun–Vie)",
        "btn_repeat_weekend_opt": "🏖 Fin de semana (Sáb–Dom)",
        "btn_repeat_weekly": "🗓 Semanal (mismo día)",
        "btn_repeat_interval": "🔢 Cada N días",
        "btn_repeat_custom_days": "☑️ Elegir días",
        "btn_repeat_monthly": "📅 Mensual (día)",
        "btn_repeat_last_weekday": "🏁 Último día laborable del mes",
        "btn_repeat_end": "⏳ Fin: {end}",
        "btn_repeat_back": "🔙 Atrás",
        "btn_repeat_done_days": "✅ Listo",
        "btn_repeat_end_none": "♾ Sin límite",
        "btn_repeat_end_count": "🔢 Tras N veces",
        "btn_repeat_end_until": "📅 Hasta una fecha",
        "repeat_interval_prompt": "¿Cada cuántos días? Envía un número (ej. 3).",
        "repeat_interval_invalid": "❌ Envía un número entero de 1 a 365.",
        "repeat_monthday_prompt": "¿Qué día del mes? Envía un número de 1 a 28.",
        "repeat_monthday_invalid": "❌ Envía un número de 1 a 28.",
        "repeat_weekday_pick_title": "Elige los días de la semana:",
        "repeat_weekday_pick_empty": "❌ Elige al menos un día.",
        "repeat_end_count_prompt": "¿Detener tras cuántas repeticiones? Envía un número de 1 a 999.",
        "repeat_end_count_invalid": "❌ Envía un número de 1 a 999.",
        "repeat_end_date_prompt": "¿Repetir hasta qué fecha? Envía DD.MM.AAAA.",
        "repeat_end_date_invalid": "❌ Envía una fecha futura como DD.MM.AAAA.",
        "repeat_saved": "✅ Repetición actualizada.",
        "main_menu_fallback": "Menú principal",
        "task_deleted": "❌ Tarea eliminada.",
        "btn_delete_undo": "↩ Deshacer eliminación",
        "task_restored": "↩️ Tarea restaurada.",
        "undo_too_late": "⌛ Demasiado tarde para deshacer.",
        "time_morning": "🌅 Mañana",
        "time_day": "☀️ Día",
        "time_evening": "🌙 Tarde",
        "time_night": "🌌 Noche",
        "brief_time_invalid_format": "❌ Introduce la hora en formato HH:MM (por ejemplo `09:30` o `23:45`).",
        "brief_time_invalid_value": "❌ Hora inválida. Horas: 0-23, minutos: 0-59.",
        "time_delta_15m": "+15m",
        "time_delta_30m": "+30m",
        "time_delta_1h": "+1h",
        "time_delta_2h": "+2h",
        "time_delta_3h": "+3h",
        "time_tomorrow": "🗓 Mañana (09:00)",
        "time_manual": "⌨️ Introducir manualmente",
        "reminder_prefix": "🔔 ",
        "brief_morning": "🌅 **¡Buenos días! Plan para hoy:**\n",
        "brief_evening_title": "🌙 **Resumen del día:**",
        "brief_evening_done": "✅ Hechas: {count}",
        "brief_evening_pending": "⏳ Pendientes/Perdidas: {count}\n",
        "brief_evening_upcoming_title": "⏰ **Todavía hoy:**",
        "brief_items_more": "…y {count} más",
        "btn_done": "✅ Hecho",
        "btn_not_today": "🚫 Hoy no",
        "btn_done_short": "✅ Sí",
        "btn_not_done_short": "❌ No",
        "wrapup_task_hint": "Tarea del resumen nocturno",
        "wrapup_done_saved": "✅ Marcada como hecha esta noche.",
        "wrapup_not_done_saved": "❌ Queda como no hecha esta noche.",
        "btn_done_add_note": "📝 Añadir nota",
        "btn_done_skip_next": "⏭ Saltar siguiente",
        "btn_done_undo": "↩ Deshacer",
        "btn_snooze": "⏰ Posponer",
        "task_done_replies": [
            "✅ *¡Bien ahí\\!*",
            "✅ *¡Genial\\!*",
            "✅ *¡Gran avance\\!*",
            "✅ *¡Muy bien hecho\\!*",
            "✅ *¡Sigues con ritmo\\!*",
            "✅ *¡Otro logro\\!*",
            "✅ *¡Excelente impulso\\!*",
        ],
        "task_done_reply": "✅ *Buen trabajo\\. Te dejo en paz\\.*",
        "already_done": "Ya marcado como hecho ✅",
        "snoozed_until": "⏰ Pospuesto hasta {time}",
        "done_note_prompt": "Envía una nota corta de finalización.",
        "done_note_saved": "✅ Nota guardada.",
        "done_skip_next_done": "⏭ Siguiente ocurrencia omitida. Nueva hora: {time}",
        "done_skip_next_failed": "❌ No pude omitir la siguiente ocurrencia de esta tarea.",
        "done_undo_done": "↩ Se deshizo la acción de hecho. La tarea vuelve a estar activa.",
        "task_settings_title": "⚙️ Ajustes de: {text}",
        "nagging_limit_prompt": "¿Cuántos mensajes de insistencia debo enviar para esta tarea? Envía un número de {min} a {max}. Actual: {count}.",
        "nagging_limit_invalid": "❌ Envía un número de {min} a {max}.",
        "nagging_limit_updated": "✅ Límite de insistencia actualizado a: {count}",
        "snooze_15m": "+15m",
        "snooze_30m": "+30m",
        "snooze_1h": "+1h",
        "snooze_2h": "+2h",
        "snooze_1d": "+1 día",
        "snooze_morning": "🌅 Mañana",
        "snooze_day": "☀️ Día",
        "snooze_evening": "🌙 Tarde",
        "snooze_night": "🌌 Noche",
        "snooze_custom": "⌨️ Personalizado",
        "parse_confirmation_prompt": "Puede que haya interpretado esto de forma ambigua.\n\n📌 Tarea: {text}\n⏰ Hora: {time}\n🎯 Confianza: {confidence}%\n\n¿Es correcto?",
        "btn_parse_confirm_yes": "✅ Sí",
        "btn_parse_confirm_time": "🕒 Elegir hora",
        "btn_parse_confirm_cancel": "❌ Cancelar",
        "missed_recovery_title": "📎 **Recuperación de tareas perdidas**\nAún tienes {count} tareas vencidas:",
        "btn_recovery_done_all": "✅ Marcar todo hecho",
        "btn_recovery_snooze_all": "⏰ +1h todo",
        "recovery_done_all_done": "✅ Se marcaron como hechas {count} tareas vencidas.",
        "recovery_snooze_all_done": "⏰ Se pospusieron {count} tareas vencidas por 1 hora.",
        "btn_missed_recovery_setup": "📎 Tareas perdidas",
        "btn_missed_recovery_on": "📎 Resumen de perdidas: ACTIVADO",
        "btn_missed_recovery_off": "📎 Resumen de perdidas: DESACTIVADO",
        "btn_missed_recovery_time": "🕒 Hora: {time}",
        "missed_recovery_time_prompt": "Escribe la hora del resumen en formato HH:MM (p. ej. `10:00`).",
        "missed_recovery_time_saved": "✅ Hora del resumen actualizada: {time}",
        "btn_completed_tasks": "📜 Completadas",
        "no_completed_tasks": "🧨 Aún no hay tareas completadas. ¡Vamos a cambiar eso!",
        "completed_header": "🏆 *Tareas completadas \\(últimos 7 días\\):*\n",
        "btn_done_task_prefix": "✅ Hecha:",
        "invalid_action": "❌ Acción inválida",
        "invalid_mode": "❌ Modo inválido",
        "unknown_snooze": "❌ Acción desconocida",
        "item_not_found": "No encontrado",
        "task_not_found": "Tarea no encontrada.",
        "snoozed_toast": "Pospuesto",
        "task_untitled": "Tarea sin título",
        "db_error": "❌ Error de base de datos. Inténtalo más tarde.",
        "habit_create_failed_long": "❌ No se pudo crear el hábito (texto demasiado largo).",
        "habit_create_failed_internal": "❌ Error interno al crear el hábito.",
        "text_too_long": "❌ Texto demasiado largo ({length} caracteres). Máximo: {max_length} caracteres.",
        "schedule_error": "❌ No se pudo programar el recordatorio. Inténtalo de nuevo.",

        # Habits
        "habits_dashboard": "🫧 **Panel de hábitos**:\nElige una plantilla o crea tu hábito diario.",
        "habit_motivation": "🔥 Impulso: {weekly_done} completadas en 7d · {active_count} hábitos activos · racha {best_current_streak} (máx {best_ever_streak}) · 💪 {avg_score}%",
        "habit_preset_water": "💧 Beber agua",
        "habit_preset_workout": "🧘 Entrenar",
        "habit_preset_rest": "🛌 Descansar",
        "habit_btn_custom": "➕ Hábito personalizado",
        "habit_btn_fluid": "🌊 Hábito flexible",
        "habit_btn_list": "📋 Mis hábitos activos",
        "habit_btn_cancel": "❌ Cancelar",
        "habit_cancelled": "Cancelado.",
        "habit_unknown": "❓ Hábito",
        "habit_selected_prompt": "Elegiste: **{habit}**\n\n¿A qué hora debo recordártelo cada día? (por ejemplo `10:00`)",
        "habit_custom_prompt": "¿Qué hábito quieres crear?\n*(por ejemplo: \"Leer 20 páginas\")*",
        "habit_time_prompt": "¡Genial! ¿A qué hora debo recordártelo cada día? (por ejemplo `10:00`)",
        "habit_default_name": "Mi hábito",
        "habit_time_retry": "❌ No pude entender la hora. Inténtalo de nuevo (por ejemplo `10:00`).",
        "habit_created": "✅ **Hábito diario creado**\nTe recordaré **{habit}** cada día a las `{time}`.",
        "habit_fluid_name_prompt": "🌊 Envía el nombre de tu hábito flexible.\n\nEjemplo: `Leer 20 páginas`",
        "habit_fluid_mode_prompt": "Elige el modo del hábito flexible:",
        "habit_fluid_mode_brief_only": "1) Solo resumen de mañana + comprobación de noche",
        "habit_fluid_mode_ask_time": "2) Preguntarme cada mañana la hora de recordatorio",
        "habit_fluid_created": "✅ **Hábito flexible creado**\nHábito: **{habit}**\nModo: {mode}",
        "habit_no_active": "📋 No tienes hábitos diarios activos.",
        "habit_list_header": "📋 **Tus hábitos diarios activos:**\n",
        "habit_list_item": "{index}. **{habit}** ({time}) · 🔥 {streak} (máx {best}) · 💪 {score}% · {mode}",
        "habit_btn_delete_n": "❌ Eliminar {index}",
        "habit_btn_back_dashboard": "🔙 Volver al panel",
        "habit_deleted_alert": "✅ Hábito eliminado.",
        "habit_deleted_followup": "Hábito eliminado. Pulsa 🫧 Hábitos para ver el panel actualizado.",
        "habit_delete_error_alert": "❌ Error al eliminar hábito.",
        "habit_mode_fixed": "hora fija",
        "habit_mode_fluid_ask_time": "flexible: preguntar hora cada mañana",
        "habit_mode_fluid_brief_only": "flexible: solo resúmenes",
        "habit_fluid_time_anytime": "en cualquier momento de hoy",
        "fluid_morning_title": "🌊 **Hábitos flexibles de hoy:**",
        "fluid_pick_time_prompt": "🌊 **Plan del día:**\nElige la hora de recordatorio para: **{habit}**",
        "fluid_evening_check": "🌙 **Antes del resumen nocturno:**\nMarca hábitos flexibles completados:",
        "fluid_done_btn_prefix": "✅ Hecho: ",
        "fluid_done_saved": "✅ Marcado como hecho para hoy.",
        "fluid_time_custom": "⌨️ Hora personalizada",
        "fluid_time_custom_prompt": "Envía la hora para hoy en formato `HH:MM` (por ejemplo `14:30`).",
        "fluid_time_invalid": "❌ Usa formato HH:MM (por ejemplo `14:30`).",
        "fluid_time_past": "❌ Esa hora ya pasó hoy.",
        "fluid_time_saved": "✅ Te recordaré hoy a las `{time}`.",
        "habit_not_today_saved": "🚫 Marcado como «hoy no». Racha reiniciada.",

        # Informes de hábitos
        "btn_habit_reports_setup": "📊 Informes de hábitos",
        "btn_habit_reports_on": "📊 Informes de hábitos: ACTIVADO",
        "btn_habit_reports_off": "📊 Informes de hábitos: DESACTIVADO",
        "btn_habit_report_day": "📅 Día: {day}",
        "btn_habit_report_time": "🕒 Hora: {time}",
        "habit_report_day_prompt": "Elige el día para tu informe de hábitos:",
        "habit_report_time_prompt": "Envía la hora del informe en formato HH:MM (por ejemplo `23:50`).",
        "habit_report_time_saved": "✅ Hora del informe actualizada: {time}",
        "habit_report_weekly_title": "📊 **Resumen semanal**",
        "habit_report_monthly_title": "📊 **Resumen mensual**",
        "habit_report_line": "🫧 {habit}: {done} de {total} ({rate}%)",
        "habit_report_total": "**Total:** ✅ {done} logrados · ❌ {not_done} fallados ({rate}%)",
        "weekday_names": ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
    }
)
