"""Russian dictionary (default)."""

from typing import Any

RU: dict[str, Any] = {
    # Menu & Commands
    "cmd_start": "👋 Привет, {name}!\nЯ **Porabot**. Я помогу тебе не прокрастинировать.\n\nВыбери действие в меню 👇",
    "cmd_help": (
        "🤖 **Команды Porabot**\n\n"
        "/start — показать главное меню\n"
        "/help — это сообщение\n"
        "/cancel — отменить текущее действие\n\n"
        "Просто напиши или перешли сообщение вроде *«напомни через 15 минут выпить воды»* — "
        "я сам распознаю время. Кнопки меню — для задач, привычек и настроек."
    ),
    "cmd_desc_start": "Главное меню",
    "cmd_desc_help": "Показать помощь",
    "cmd_desc_cancel": "Отменить текущее действие",
    "btn_new_task": "➕ Новая задача",
    "btn_my_tasks": "📅 Мои задачи",
    "btn_settings": "⚙️ Настройки",
    "btn_habits": "🫧 Привычки",
    
    # Language Selection
    "choose_language": "Пожалуйста, выберите язык / Please choose a language:",
    "lang_ru": "🇷🇺 Русский",
    "lang_en": "🇬🇧 English",
    "lang_es": "🇪🇸 Español",
    "lang_set": "✅ Язык установлен на Русский.",

    # Settings
    "settings_text": "⚙️ **Настройки**\n\n🌍 Твой часовой пояс: `{timezone}`\n🗣 Язык интерфейса: Русский\n😴 Тихие часы: `{quiet_hours}`\n\nЕсли время напоминаний скачет, проверь пояс.",
    "btn_change_tz": "🌍 Сменить часовой пояс",
    "btn_change_lang": "🗣 Сменить язык",
    "btn_quiet_hours_setup": "😴 Тихие часы",
    "btn_quiet_on": "😴 Тихие часы: ВКЛ",
    "btn_quiet_off": "😴 Тихие часы: ВЫКЛ",
    "btn_quiet_start": "🌙 Начало: {time}",
    "btn_quiet_end": "🌅 Конец: {time}",
    "quiet_hours_summary": "{status} ({start}–{end})",
    "quiet_time_prompt": "Напиши время для тихих часов в формате HH:MM (например, `23:00`).",
    "quiet_time_invalid": "❌ Введи время в формате HH:MM (например, `23:00`).",
    "quiet_time_saved": "✅ Время тихих часов обновлено: `{time}`",
    "choose_tz": "Выбери свой часовой пояс:",
    "tz_manual_prompt": "Отправь только смещение UTC: `+5`, `0`, `-6` или известное получасовое смещение вроде `+5:30`.",
    "tz_manual_button": "⌨️ Ввести вручную",
    "tz_success": "✅ Часовой пояс: `{tz}`\n\nВремя уже созданных задач не пересчитывается — они сработают в прежнее время. При необходимости поправь их вручную.",
    "tz_invalid": "❌ Неверное смещение. Отправь `+5`, `0` или `-6` (диапазон: от -12 до +14).",
    "tz_label_america_new_york": "Восток США (EST/EDT)",
    "tz_label_america_chicago": "Центр США (CST/CDT)",
    "tz_label_america_denver": "Горный США (MST/MDT)",
    "tz_label_america_los_angeles": "Запад США (PST/PDT)",
    "tz_label_europe_london": "Лондон (GMT/BST)",
    "tz_label_europe_berlin": "Берлин (CET/CEST)",
    "tz_label_europe_kyiv": "Киев",
    "tz_label_europe_moscow": "Москва",
    "tz_label_asia_dubai": "Дубай",
    "tz_label_asia_almaty": "Алматы",
    "tz_label_asia_tokyo": "Токио",
    "tz_label_asia_singapore": "Сингапур",
    "tz_label_utc": "UTC",
    "btn_toggle_utc_off": "🕒 Показывать смещение UTC: ВЫКЛ",
    "btn_toggle_utc_on": "🕒 Показывать смещение UTC: ВКЛ",
    "btn_clear_all": "🗑 Очистить всё",
    "btn_clear_all_confirm": "✅ Да, удалить всё",
    "btn_clear_all_cancel": "↩ Отмена",
    "clear_all_confirm_text": "⚠️ Это навсегда удалит **все** задачи, привычки и настройки.\n\nТочно продолжить?",
    "clear_all_done": "✅ Все данные удалены. Начинаем с нуля.",
    
    # Custom Daily Briefs Settings
    "btn_briefs_setup": "📋 Настройка сводок",
    "btn_briefs_on": "🔔 Ежедневные сводки: ВКЛ",
    "btn_briefs_off": "🔕 Ежедневные сводки: ВЫКЛ",
    "btn_morning_brief": "🌅 Утренняя: {time}",
    "btn_evening_brief": "🌙 Вечерняя: {time}",
    "choose_hour": "Напиши точное время для сводки (Например '09:30' или '23:45'):",
    "brief_time_invalid_format": "❌ Введи время в формате HH:MM (например `09:30` или `23:45`).",
    "brief_time_invalid_value": "❌ Некорректное время. Часы: 0-23, минуты: 0-59.",
    "btn_back_settings": "🔙 Назад",

    # Tasks List
    "no_tasks": "🎉 У тебя нет активных задач. Отдыхай!",
    "tasks_header": "📋 *Твои задачи:*\n",
    "tasks_page_indicator": "📄 {page}/{total}",
    "btn_prev_page": "◀️",
    "btn_next_page": "▶️",
    "btn_delete_prefix": "🗑 Удалить:",
    "btn_refresh": "🔄 Обновить",
    "btn_close": "❌ Закрыть",

    # Wizard
    "enter_task": "Напиши, о чем напомнить.\nМожно сразу с временем: *\"Позвонить маме завтра в 18:00\"*.",
    "parse_error": "Ошибка обработки текста. Проверь формат.",
    "ask_time": "Ок, задача: \"{text}\".\nКогда напомнить?",
    "try_again_manual": "Попробуй снова написать задачу ЦЕЛИКОМ, включая дату и время.",
    "time_in_past": "⏰ Это время уже прошло. Укажи время в будущем.",
    "forwarded_from": "Переслано от",
    
    # Confirmation logic -> Edit Logic
    "preview": "✅ *Задача сохранена\\!*\n📌 {text}\n⏰ {time}",
    "btn_repeat_prefix": "🔁 Повтор:",
    "btn_nagging_prefix": "{icon} Зуд (Nagging):",
    "btn_nagging_repeats_prefix": "🔁 Повторы зуда: {count}",
    "btn_edit_time": "🕒 Изменить время",
    "btn_delete": "🗑 Удалить",
    "btn_task_settings": "⚙️ Настройки",
    "status_on": "ВКЛ",
    "status_off": "ВЫКЛ",
    "repeat_none": "Нет",
    "repeat_day": "День",
    "repeat_weekdays": "Будни",
    "repeat_week": "Неделя",
    
    "main_menu_fallback": "Главное меню",
    "task_deleted": "❌ Задача удалена.",  # single definition — canonical value
    "btn_delete_undo": "↩ Отменить удаление",
    "task_restored": "↩️ Задача восстановлена.",
    "undo_too_late": "⌛ Время для отмены истекло.",
    "what_next": "Что дальше?",
    "cmd_cancel": "❌ Создание напоминания отменено.",
    "btn_cancel": "❌ Отмена",

    # Time Selection Keyboard
    "time_morning": "🌅 Утро",
    "time_day": "☀️ День",
    "time_evening": "🌙 Вечер",
    "time_night": "🌌 Ночь",
    "time_delta_15m": "+15м",
    "time_delta_30m": "+30м",
    "time_delta_1h": "+1ч",
    "time_delta_2h": "+2ч",
    "time_delta_3h": "+3ч",
    "time_tomorrow": "🗓 Завтра (09:00)",
    "time_manual": "⌨️ Ввести вручную",

    # Reminders / Scheduler
    "reminder_prefix": "🔔 ",
    "brief_morning": "🌅 **Доброе утро! План на сегодня:**\n",
    "brief_evening_title": "🌙 **Итоги дня:**",
    "brief_evening_done": "✅ Выполнено: {count}",
    "brief_evening_pending": "⏳ Осталось/Пропущено: {count}\n",
    "brief_items_more": "…и ещё {count}",
    "btn_done": "✅ Сделано",
    "btn_not_today": "🚫 Не сегодня",
    "btn_done_short": "✅ Да",
    "btn_not_done_short": "❌ Нет",
    "wrapup_task_hint": "Задача из вечерней сводки",
    "wrapup_done_saved": "✅ Отмечено выполненным на сегодня.",
    "wrapup_not_done_saved": "❌ Оставлено невыполненным на сегодня.",
    "btn_done_add_note": "📝 Добавить заметку",
    "btn_done_skip_next": "⏭ Пропустить следующий",
    "btn_done_undo": "↩ Отменить",
    "btn_snooze": "⏰ Отложить",
    "task_done_replies": [
        "✅ *Отлично\\!*",
        "✅ *Супер\\!*",
        "✅ *Классный ход\\!*",
        "✅ *Так держать\\!*",
        "✅ *Вот это темп\\!*",
        "✅ *Ещё одна победа\\!*",
        "✅ *Сильный результат\\!*",
    ],
    "task_done_reply": "✅ *Красавчик\\. Отстал\\.*",
    "already_done": "Уже выполнено ✅",
    "invalid_action": "❌ Неверное действие",
    "invalid_mode": "❌ Неверный режим",
    "unknown_snooze": "❌ Неизвестное действие",
    "item_not_found": "Не найдено",
    "task_not_found": "Задача не найдена.",
    "snoozed_toast": "Отложено!",
    "task_untitled": "Без названия",
    "snoozed_until": "⏰ Отложено до {time}",
    "done_note_prompt": "Отправь короткую заметку о выполнении.",
    "done_note_saved": "✅ Заметка сохранена.",
    "done_skip_next_done": "⏭ Следующее срабатывание пропущено. Новое время: {time}",
    "done_skip_next_failed": "❌ Не удалось пропустить следующее срабатывание.",
    "done_undo_done": "↩ Отметка выполнения отменена. Задача снова активна.",
    "task_settings_title": "⚙️ Настройки задачи: {text}",
    "nagging_limit_prompt": "Сколько повторных сообщений присылать для этой задачи? Отправь число от {min} до {max}. Сейчас: {count}.",
    "nagging_limit_invalid": "❌ Отправь число от {min} до {max}.",
    "nagging_limit_updated": "✅ Лимит повторов зуда установлен: {count}",

    # Snooze options
    "snooze_15m": "+15м",
    "snooze_30m": "+30м",
    "snooze_1h": "+1ч",
    "snooze_2h": "+2ч",
    "snooze_1d": "+1 день",
    "snooze_morning": "🌅 Утро",
    "snooze_day": "☀️ День",
    "snooze_evening": "🌙 Вечер",
    "snooze_night": "🌌 Ночь",
    "snooze_custom": "⌨️ Свой вариант",
    "parse_confirmation_prompt": "Я мог распознать время неоднозначно.\n\n📌 Задача: {text}\n⏰ Время: {time}\n🎯 Уверенность: {confidence}%\n\nСохраняем так?",
    "btn_parse_confirm_yes": "✅ Да",
    "btn_parse_confirm_time": "🕒 Выбрать время",
    "btn_parse_confirm_cancel": "❌ Отмена",

    # Missed-task recovery
    "missed_recovery_title": "📎 **Восстановление пропущенных задач**\nУ тебя осталось {count} просроченных задач:",
    "btn_recovery_done_all": "✅ Сделать всё",
    "btn_recovery_snooze_all": "⏰ +1ч всем",
    "recovery_done_all_done": "✅ Отмечено выполненными: {count} просроченных задач.",
    "recovery_snooze_all_done": "⏰ Отложено на 1 час: {count} просроченных задач.",
    "btn_missed_recovery_setup": "📎 Пропущенные задачи",
    "btn_missed_recovery_on": "📎 Дайджест пропущенных: ВКЛ",
    "btn_missed_recovery_off": "📎 Дайджест пропущенных: ВЫКЛ",
    "btn_missed_recovery_time": "🕒 Время: {time}",
    "missed_recovery_time_prompt": "Введи время дайджеста в формате ЧЧ:ММ (например, `10:00`).",
    "missed_recovery_time_saved": "✅ Время дайджеста обновлено: {time}",

    # Completed tasks section
    "btn_completed_tasks": "📜 Выполненные",
    "no_completed_tasks": "🧨 Выполненных задач еще нет. Давай исправлять это!",
    "completed_header": "🏆 *Выполненные задачи \\(за 7 дней\\):*\n",
    "btn_done_task_prefix": "✅ Готово:",

    # Habits
    "habits_dashboard": "🫧 **Панель привычек**:\nВыбери шаблон или создай свою ежедневную привычку.",
    "habit_motivation": "🔥 Импульс: {weekly_done} выполнений за 7 дней · {active_count} активных привычек · серия {best_current_streak} (рекорд {best_ever_streak})",
    "habit_preset_water": "💧 Пить воду",
    "habit_preset_workout": "🧘 Тренировка",
    "habit_preset_rest": "🛌 Отдых",
    "habit_btn_custom": "➕ Своя привычка",
    "habit_btn_fluid": "🌊 Гибкая привычка",
    "habit_btn_list": "📋 Мои активные привычки",
    "habit_btn_cancel": "❌ Отмена",
    "habit_cancelled": "Отменено.",
    "habit_unknown": "❓ Привычка",
    "habit_selected_prompt": "Выбрано: **{habit}**\n\nВо сколько напоминать каждый день? (например, `10:00`)",
    "habit_custom_prompt": "Какую привычку хочешь добавить?\n*(например: \"Читать 20 страниц\" или \"Учить Python\")*",
    "habit_time_prompt": "Отлично! Во сколько напоминать каждый день? (например, `10:00`)",
    "habit_default_name": "Моя привычка",
    "habit_time_retry": "❌ Не удалось распознать время. Попробуй снова (например, `10:00`).",
    "habit_created": "✅ **Ежедневная привычка создана!**\nБуду напоминать: **{habit}** каждый день в `{time}`.",
    "habit_fluid_name_prompt": "🌊 Отправь название гибкой привычки.\n\nНапример: `Прочитать 20 страниц`",
    "habit_fluid_mode_prompt": "Выбери режим гибкой привычки:",
    "habit_fluid_mode_brief_only": "1) Только утренняя сводка + вечерняя проверка",
    "habit_fluid_mode_ask_time": "2) Каждое утро спрашивать время напоминания",
    "habit_fluid_created": "✅ **Гибкая привычка создана!**\nПривычка: **{habit}**\nРежим: {mode}",
    "habit_create_failed_long": "❌ Не удалось создать привычку (слишком длинный текст).",
    "habit_create_failed_internal": "❌ Внутренняя ошибка при создании привычки.",
    "habit_no_active": "📋 Активных ежедневных привычек пока нет. Нажми «➕ Своя привычка» или выбери шаблон.",
    "habit_list_header": "📋 **Твои активные ежедневные привычки:**\n",
    "habit_list_item": "{index}. **{habit}** ({time}) · 🔥 {streak} (рекорд {best}) · {mode}",
    "habit_btn_delete_n": "❌ Удалить {index}",
    "habit_btn_back_dashboard": "🔙 Назад к панели",
    "habit_deleted_alert": "✅ Привычка удалена!",
    "habit_deleted_followup": "Привычка удалена. Нажми 🫧 Привычки, чтобы открыть обновлённую панель.",
    "habit_delete_error_alert": "❌ Ошибка при удалении привычки.",
    "habit_mode_fixed": "фиксированное время",
    "habit_mode_fluid_ask_time": "гибкая: спросить время утром",
    "habit_mode_fluid_brief_only": "гибкая: только сводки",
    "habit_fluid_time_anytime": "в любое время сегодня",
    "fluid_morning_title": "🌊 **Гибкие привычки на сегодня:**",
    "fluid_pick_time_prompt": "🌊 **План на день:**\nВыбери время напоминания сегодня для: **{habit}**",
    "fluid_evening_check": "🌙 **Перед вечерней сводкой:**\nОтметь выполненные гибкие привычки:",
    "fluid_done_btn_prefix": "✅ Сделано: ",
    "fluid_done_saved": "✅ Отмечено как выполненное за сегодня.",
    "fluid_time_custom": "⌨️ Свое время",
    "fluid_time_custom_prompt": "Отправь время напоминания на сегодня в формате `HH:MM` (например `14:30`).",
    "fluid_time_invalid": "❌ Используй формат HH:MM (например `14:30`).",
    "fluid_time_past": "❌ Это время сегодня уже прошло.",
    "fluid_time_saved": "✅ Напомню сегодня в `{time}`.",
    "habit_not_today_saved": "🚫 Отмечено «не сегодня». Стрик сброшен.",

    # Отчёты по привычкам
    "btn_habit_reports_setup": "📊 Отчёты по привычкам",
    "btn_habit_reports_on": "📊 Отчёты по привычкам: ВКЛ",
    "btn_habit_reports_off": "📊 Отчёты по привычкам: ВЫКЛ",
    "btn_habit_report_day": "📅 День: {day}",
    "btn_habit_report_time": "🕒 Время: {time}",
    "habit_report_day_prompt": "Выбери день для отчёта по привычкам:",
    "habit_report_time_prompt": "Отправь время отчёта в формате HH:MM (например `23:50`).",
    "habit_report_time_saved": "✅ Время отчёта обновлено: {time}",
    "habit_report_weekly_title": "📊 **Итоги недели**",
    "habit_report_monthly_title": "📊 **Итоги месяца**",
    "habit_report_line": "🫧 {habit} — {done}/{total} ({rate}%)",
    "habit_report_total": "**Итого:** ✅ {done} · ❌ {not_done} ({rate}%)",
    "weekday_names": ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    
    # Error messages (SECURITY FIX: Added missing keys)
    "text_too_long": "❌ Текст слишком длинный ({length} символов). Максимум: {max_length} символов.",
    "schedule_error": "❌ Не удалось запланировать напоминание. Попробуйте снова.",
    "db_error": "❌ Ошибка базы данных. Попробуйте позже.",
}
